name: Web Testing

on:
  workflow_dispatch:

jobs:
  scrapeinside3:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ vars.BASE_URL }}
      LOG_TRG: ${{ vars.LOG_STR }}
      CON_STR_COMS: ${{ vars.CON_STR_COMS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install required system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip xvfb libxi6 libnss3 libxss1 libindicator7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install \
            selenium \
            webdriver-manager \
            beautifulsoup4 \
            pandas \
            selenium-stealth \
            azure-storage-blob

      - name: Run Selenium in headless mode
        run: |
          python test.py
