name: Go Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'  # Specify the Go version you want to use

    - name: Install dependencies
      run: go mod tidy

    - name: Build Go application
      run: go build -o myapp

    - name: Run Go application
      run: ./myapp
